[Printer]
#PortName = "/dev/ttyACM0"
#PortName = "/dev/pts/42"
PortName = "/dev/pts/1"
BaudRate = 115200

[Camera]
CameraSerialNumber = "000007601060"
OutputDir = "/tmp/timelapse-serial-captures"

# All of this is optional, if omitted these default value will be used
[FFMPEG]
OutputVideoResolution = "3246x2158"
Codec = "libx264"
PixelFormat = "yuv420p"
FramesPerSecond = "24"
