[Printer]
#PortName = "/dev/ttyACM0"
PortName = "/dev/pts/42"
BaudRate = 115200

[Camera]
CameraSerialNumber = "000007601060"
OutputDir = "/tmp/timelapse-serial-captures"

# Optional
LiveFeedURL = "http://prusaberry.lan:8000/stream.mjpg"

# All of this is optional, if omitted these default value will be used
[FFMPEG]
OutputVideoResolution = "3246x2158"
Codec = "libx264"
PixelFormat = "yuv420p"
FramesPerSecond = "24"
TimeoutInMinutes = 20

[Web]
ThumbnailCreationMaxGoroutines = 10
